// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:123456789:web:abcdefghijklmnop',
    messagingSenderId: '123456789',
    projectId: 'fruit-factory-stock-dev',
    authDomain: 'fruit-factory-stock-dev.firebaseapp.com',
    databaseURL: 'https://fruit-factory-stock-dev.firebaseio.com',
    storageBucket: 'fruit-factory-stock-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:123456789:android:abcdefghijklmnop',
    messagingSenderId: '123456789',
    projectId: 'fruit-factory-stock-dev',
    databaseURL: 'https://fruit-factory-stock-dev.firebaseio.com',
    storageBucket: 'fruit-factory-stock-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:123456789:ios:abcdefghijklmnop',
    messagingSenderId: '123456789',
    projectId: 'fruit-factory-stock-dev',
    databaseURL: 'https://fruit-factory-stock-dev.firebaseio.com',
    storageBucket: 'fruit-factory-stock-dev.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:123456789:ios:abcdefghijklmnop',
    messagingSenderId: '123456789',
    projectId: 'fruit-factory-stock-dev',
    databaseURL: 'https://fruit-factory-stock-dev.firebaseio.com',
    storageBucket: 'fruit-factory-stock-dev.appspot.com',
  );
}
